apiVersion: apps/v1
kind: Deployment
metadata:
  name: spemajorf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spemajorf
  template:
    metadata:
      labels:
        app: spemajorf
    spec:
      containers:
        - name: spemajorf-container
          image: aryanpatel111/spe_frontend
          ports:
            - containerPort: 3000
